Kickstart:	A B C D

A:	A.cpp
	g++ -o A A.cpp -std=c++17 -O3

B:	B.cpp
	g++ -o B B.cpp -std=c++17 -O3

C:	C.cpp
	g++ -o C C.cpp -std=c++17 -O3

D:	D.cpp
	g++ -o D D.cpp -std=c++17 -O3

clean:
	rm -rf A B C D